# Oefening _NumPy_ in les 1

Laten we beginnen met het importeren van _NumPy_:

In [1]:
import numpy

Een één-dimensionale array met de getallen 0 tot en met 5:

In [2]:
x = numpy.array([0,1,2,3,4,5])
x

array([0, 1, 2, 3, 4, 5])

Of zo:

In [3]:
x2 = numpy.arange(6)
x2

array([0, 1, 2, 3, 4, 5])

De arrays `x` en `x2` hebben dezelfde dimensies:

In [4]:
print("De dimensie van x is {}.".format(x.shape))
print("De dimensie van x2 is {}.".format(x2.shape))

De dimensie van x is (6,).
De dimensie van x2 is (6,).


De array omvormen naar twee dimensies:

In [5]:
x = numpy.reshape(x, (2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

Of laat _NumPy_ de grootte van de tweede dimensie zelf bepalen:

In [6]:
x2 = numpy.reshape(x2, (2,-1))
x2

array([[0, 1, 2],
       [3, 4, 5]])

De dimensies zijn nu als volgt:

In [7]:
print("De dimensie van x is {}.".format(x.shape))
print("De dimensie van x2 is {}.".format(x2.shape))

De dimensie van x is (2, 3).
De dimensie van x2 is (2, 3).


En het datatype:

In [8]:
print("Het datatype van x is {}.".format(x.dtype))
print("Het datatype van x2 is {}.".format(x2.dtype))

Het datatype van x is int32.
Het datatype van x2 is int32.


Maak een kopie van `x` genaamd `y`:

In [9]:
y = x.copy()
y

array([[0, 1, 2],
       [3, 4, 5]])

**Let op!** `x = y` maakt geen kopie, maar kopieert alleen de _referentie_ naar hetzelfde object. Met andere woorden, `x` en `y` zijn vanaf dat moment twee namen voor _dezelfde_ array:

In [10]:
y2 = x2
x2[0,0] = 99
print("x2 =\n {}\n".format(x2))
print("y2 =\n {}".format(y2))

x2 =
 [[99  1  2]
 [ 3  4  5]]

y2 =
 [[99  1  2]
 [ 3  4  5]]


Een transpose 'klapt' de matrix om:

In [11]:
x = numpy.transpose(x)
x

array([[0, 3],
       [1, 4],
       [2, 5]])

Of zo:

In [12]:
y = y.T
y

array([[0, 3],
       [1, 4],
       [2, 5]])

Alle waarden van _y_ verdubbelen:

In [13]:
y = 2 * y
y

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

Concateneren kan verticaal en horizontaal:

In [15]:
z = numpy.vstack((x,y))
z1 = numpy.concatenate((x,y),axis=1)
z2 = numpy.c_[x,y]

print("z =\n {}\n".format(z))
print("z1 =\n {}\n".format(z1))
print("z2 =\n {}".format(z2))

z =
 [[ 0  3]
 [ 1  4]
 [ 2  5]
 [ 0  6]
 [ 2  8]
 [ 4 10]]

z1 =
 [[ 0  3  0  6]
 [ 1  4  2  8]
 [ 2  5  4 10]]

z2 =
 [[ 0  3  0  6]
 [ 1  4  2  8]
 [ 2  5  4 10]]


Voor het gemiddelde maakt de vorm natuurlijk niet uit:

In [24]:
print("Gemiddelde van z is: {}".format(z.mean()))
print("Standaarddeviatie van z is: {:0.4f}\n".format(numpy.std(z)))
print("Gemiddelde van z1 is: {}".format(z1.mean()))
print("Standaarddeviatie van z1 is: {:0.4f}".format(numpy.std(z1)))      

Gemiddelde van z is: 3.75
Standaarddeviatie van z is: 2.9756

Gemiddelde van z1 is: 3.75
Standaarddeviatie van z1 is: 2.9756
